# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-04 17:38
from __future__ import unicode_literals

from django.db import migrations, models
from django.core.paginator import Paginator
import uuid


def generate_uuid(apps, schema):
    Notification = apps.get_model('notifications', 'Notification')
    notifications_paginator = Paginator(Notification.objects.all(), 100)
    for page_number in range(1, notifications_paginator.num_pages+1):
        for notification in notifications_paginator.page(page_number).object_list:
            notification.uuid = uuid.uuid4()
            notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20160504_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.RunPython(generate_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
