# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-05 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='actor_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor', to='contenttypes.ContentType'),
        ),
    ]
