# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-27 14:38
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F
from django.utils import timezone


def forwards(apps, schema_editor):
    Notification = apps.get_model('notifications', 'notification')

    Notification.objects.filter(deleted=True).update(archived_at=timezone.now())
    Notification.objects.filter(unread=False).update(read_at=timezone.now())
    Notification.objects.all().update(created_at=F('timestamp'))


def backwards(apps, schema_editor):
    Notification = apps.get_model('notifications', 'notification')

    Notification.objects.filter(archived_at__isnull=False).update(deleted=True)
    Notification.objects.filter(read_at__isnull=False).update(unread=False)
    Notification.objects.all().update(timestamp=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20190327_1538'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
