# Generated by Django 2.1.8 on 2019-04-27 21:26

from django.conf import settings
from django.db import migrations
from django.db.models import Index
from django.utils import version

_version = version.get_version_tuple(version.get_version())
if _version[0] >= 4 and _version[1] >= 2:
    _operations = [
        migrations.AddIndex(
            model_name="notification",
            index=Index(fields=("recipient", "unread"), name="recipient_unread_idx"),
        ),
    ]
else:
    _operations = [
        migrations.AlterIndexTogether(
            name="notification",
            index_together={("recipient", "unread")},
        ),
    ]


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0007_add_timestamp_index"),
    ]

    operations = _operations
