# Generated by Django 2.2.11 on 2020-03-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_index_together_recipient_unread'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.FileField(max_length=255, upload_to='')),
                ('slug', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'abstract': False,
                'swappable': 'NOTIFICATIONS_NOTIFICATIONTEMPLATE_MODEL',
            },
        ),
    ]
