# Generated by Django 4.0.2 on 2022-02-14 19:40

from django.db import migrations, models
from django.db.models import F


def copy_data_column(apps, schema_editor):
    notification_model = apps.get_model('notifications', 'Notification')
    db_alias = schema_editor.connection.alias
    notification_model.objects.using(db_alias).update(data=F('data_tmp'))


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_index_together_recipient_unread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='data',
            new_name='data_tmp',
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(copy_data_column, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='notification',
            name='data_tmp',
        ),
    ]
