# Generated by Django 4.1.3 on 2022-11-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_index_together_recipient_unread"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='notification',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'unread'], name='notificatio_recipie_8bedf2_idx'),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["actor_content_type", "actor_object_id"],
                name="notificatio_actor_c_4f870b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="notificatio_target__dfbaf5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["action_object_content_type", "action_object_object_id"],
                name="notificatio_action__6e12f7_idx",
            ),
        ),
    ]
