# Generated by Django 3.2.13 on 2022-05-23 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('notifications', '0008_index_together_recipient_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sites.site'),
            preserve_default=False,
        ),
    ]
