# Generated by Django 4.2.1 on 2023-05-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0009_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="data",
            field=models.JSONField(blank=True, null=True, verbose_name="data"),
        ),
    ]
