# Generated by Django 3.2.13 on 2022-05-23 14:43

from django.conf import settings
from django.db import migrations
import django.db.models.manager
import notifications.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0009_notification_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', notifications.base.models.NotificationOnSiteManagerWithQuerySet()),
            ],
        ),
        migrations.AlterIndexTogether(
            name='notification',
            index_together={('site', 'recipient', 'unread')},
        ),
    ]
