# Generated by Django 2.2.11 on 2020-03-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notificationtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='icon',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
