# Generated by Django 4.2.1 on 2023-06-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0010_alter_notification_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="new_level",
            field=models.IntegerField(
                choices=[(1, "Success"), (2, "Info"), (3, "Warning"), (4, "Error")], default=2, verbose_name="level"
            ),
        ),
    ]
