# Generated by Django 4.2.1 on 2023-06-02 00:05

from django.db import migrations
from ..base.models import NotificationLevel

def copy_level(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    Notification.objects.filter(level="success").update(new_level=NotificationLevel.SUCCESS)
    Notification.objects.filter(level="info").update(new_level=NotificationLevel.INFO)
    Notification.objects.filter(level="warning").update(new_level=NotificationLevel.WARNING)
    Notification.objects.filter(level="error").update(new_level=NotificationLevel.ERROR)


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0011_notification_new_level"),
    ]

    operations = [
        migrations.RunPython(copy_level),
    ]
