# Generated by Django 4.2.1 on 2023-06-16 01:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0012_auto_20230601_1905"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="level",
        ),
    ]
