# Generated by Django 4.2.1 on 2023-06-16 01:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0013_remove_notification_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="new_level",
            new_name="level",
        ),
    ]
