# Generated by Django 4.2.11 on 2024-05-03 00:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0015_alter_notification_action_object_content_type_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_8bedf2_idx",
            old_fields=("recipient", "unread"),
        ),
    ]
