# Generated by Django 4.2.11 on 2024-05-03 00:08

from django.db import migrations
from django.db.models import Index
from django.utils import version

major, minor, *_ = version.get_version_tuple(version.get_version())
version = major * 10 + minor
if version >= 42:
    _operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_8bedf2_idx",
            old_fields=("recipient", "unread"),
        ),
    ]
else:
    _operations = []


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0015_alter_notification_action_object_content_type_and_more"),
    ]

    operations = _operations
