# Generated by Django 4.2.11 on 2024-05-16 22:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0016_rename_notification_recipient_unread_notificatio_recipie_8bedf2_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, serialize=False, null=True),
        ),
    ]
