# Generated by Django 4.2.11 on 2024-05-16 22:50

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    for row in Notification.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0017_remove_notification_recipient_unread_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
