# Generated by Django 4.2.11 on 2024-05-16 22:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0018_auto_20240516_1750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False, unique=True),
        ),
    ]
